aws_secrets_manager:
  cache_ttl: 300

awssm_oauth:
  certificate_cache_ttl: 300
  certificate_region: "us-east-2"
  token_cache_ttl: 300
  token_cache_size: 10
  oauth_url: "http://localhost:8090"
  jwt_claims_map: '{"iss":"sample_issuer", "sub":"sample_sub", "aud":"sample_aud"}'
  jwt_duration: 300
  http_retry_attempts: 3
  http_retry_min_wait: 3
  http_retry_max_wait: 10

log_config:
  level: "info"
