aws_secrets_manager:
  cache_ttl: 300

awssm_oauth:
  certificate_cache_ttl: 300
  certificate_secret_id: "testSecret"
  token_cache_ttl: 300
  token_cache_size: 10
  oauth_url: "https://aws-sm-oauth-demo.hasura.app/api/rest/oauth"
  oauth_client_id: "sample_client_id"
  jwt_claims_map: '{"iss":"sample_issuer", "sub":"sample_sub", "aud":"sample_aud"}'
  jwt_duration: 300

log_config:
  level: "info"
