azure_api:
  type: file_azure_key_vault
  vault_url: "https://karthikvt26-hsm.vault.azure.net/"
  secret_name: "api"
  secret_version: "c6f780b8313a4d3e97779672f3edb9d8"
  path: api_secret
  refresh: 3  # Refresh every 60 seconds

aws_secrets_manager:
  type: "proxy_aws_secrets_manager"
  cache_ttl: 300

awssm_oauth:
  type: "proxy_awssm_oauth"
  certificate_cache_ttl: 300
  certificate_region: "us-east-2"
  token_cache_ttl: 300
  token_cache_size: 10
  oauth_url: "http://localhost:8090/oauth"
  jwt_claims_map: '{"aud":"sample_aud"}'
  jwt_duration: 300
  http_retry_attempts: 3
  http_retry_min_wait: 3
  http_retry_max_wait: 10

awssm_oauth2:
  type: "proxy_awssm_oauth"
  certificate_cache_ttl: 200
  certificate_region: "us-east-2"
  token_cache_ttl: 200
  token_cache_size: 20
  oauth_url: "http://localhost:8090/oauth"
  jwt_claims_map: '{"aud":"sample_aud"}'
  jwt_duration: 200
  http_retry_attempts: 2
  http_retry_min_wait: 2
  http_retry_max_wait: 8


aws_secrets_manager_file:
  type: "file_aws_secrets_manager"
  region: "us-east-2"
  refresh: 300
  secret_id: testSecret
  path: ./testsecret

aws_secrets_manager_file_json:
  type: "file_aws_secrets_manager"
  region: "us-east-2"
  refresh: 300
  secret_id: testJsonSecret
  path: ./testsecretJson
  template: postgres://##secret.username##:##secret.password##@##secret.host##:##secret.port##/dbname

aws_iam_auth_rds:
  type: "file_aws_iam_auth_rds"
  region: "eu-north-1"
  db_name: "postgres"
  db_user: "iam_user"
  db_host: "database_host"
  db_port: 5432
  path: /path/to/token_file
  template: host=##.db_host## port=##.db_port## dbname=##.db_name## user=##.db_user## password=##.password##

log_config:
  level: "info"

refresh_config:
  endpoint: /refresh
