[aws_secrets_manager]
cache_ttl = 300

[awssm_oauth]
certificate_cache_ttl = 300
certificate_secret_id = "testSecret"
token_cache_ttl = 300
token_cache_size = 10
oauth_url = "http://localhost:8090"
oauth_client_id = "mock_client_id"
jwt_claims_map = '{"sub":"mocksub", "other_claim":"other_claim"}'
jwt_expiration = 300
