apiVersion: apps/v1
kind: Deployment
metadata:
  name: secrets-management-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hasura-secrets-management-proxy
  template:
    metadata:
      labels:
        app: hasura-secrets-management-proxy
    spec:
      serviceAccountName: hasura-secrets-management-proxy-service-account
      containers:
        - name: secrets-management-proxy
          image: varundey/test-repo:amd64
          imagePullPolicy: Always
          volumeMounts:
            - name: secrets-management-proxy-configmap
              mountPath: /config.yaml
              subPath: config.yaml
          ports:
            - containerPort: 8080
          env:
            - name: AWS_REGION
              value: "us-west-2"
      volumes:
        - name: secrets-management-proxy-configmap
          configMap:
            name: secrets-management-proxy
            items:
              - key: config.yaml
                path: config.yaml
