apiVersion: apps/v1
kind: Deployment
metadata:
  name: hasura-secret-refresh-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hasura-secret-refresh
  template:
    metadata:
      labels:
        app: hasura-secret-refresh
    spec:
      serviceAccountName: jpmc-secret-management-service-account-2
      containers:
        - name: hasura-secret-refresh
          image: varundey/test-repo:amd64
          imagePullPolicy: Always
          volumeMounts:
            - name: hasura-secret-refresh-configmap
              mountPath: /config.yaml
              subPath: config.yaml
          ports:
            - containerPort: 8080
          env:
            - name: AWS_REGION
              value: "us-west-2"
      volumes:
        - name: hasura-secret-refresh-configmap
          configMap:
            name: hasura-secret-refresh-configmap
            items:
              - key: config.yaml
                path: config.yaml
