apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hasura
    hasuraService: custom
  name: hasura
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hasura
  template:
    metadata:
      labels:
        app: hasura
    spec:
      serviceAccountName: secrets-management-proxy-service-account
      containers:
        - image: hasura/graphql-engine:v2.34.0
          imagePullPolicy: IfNotPresent
          name: hasura
          env:
            - name: HASURA_GRAPHQL_DATABASE_URL
              value: postgres://username:password@host:port/db
            - name: HASURA_GRAPHQL_ADMIN_SECRET
              value: mysecretkey
            ## enable the console served by server
            - name: HASURA_GRAPHQL_ENABLE_CONSOLE
              value: "true"
            ## enable debugging mode. It is recommended to disable this in production
            - name: HASURA_GRAPHQL_DEV_MODE
              value: "true"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          resources: {}
          volumeMounts:
            - name: shared-secret-volume
              mountPath: /secret
        - image: hasuraci/secrets-management-proxy:v2.33.0-beta.1
          name: secrets-management-proxy
          imagePullPolicy: Always
          ports:
            - containerPort: 5353
          volumeMounts:
            - name: secrets-management-proxy-configmap
              mountPath: /config.yaml
              subPath: config.yaml
            - name: shared-secret-volume
              mountPath: /secret
      volumes:
        - name: secrets-management-proxy-configmap
          configMap:
            name: secrets-management-proxy
            items:
              - key: config.yaml
                path: config.yaml
        - name: shared-secret-volume
          emptyDir: { }
