apiVersion: apps/v1
kind: Deployment
metadata:
  name: hasura-secret-refresh-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hasura-secret-refresh
  template:
    metadata:
      labels:
        app: hasura-secret-refresh
    spec:
      serviceAccountName: jpmc-secret-management-service-account-2
      containers:
        - name: hasura-secret-refresh
          image: varundey/test-repo:amd64
          ports:
            - containerPort: 8080
