apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::528956693660:role/jpmc-secret-management-service-account-role-2
  labels:
    app.kubernetes.io/managed-by: eksctl
  name: jpmc-secret-management-service-account-2
