apiVersion: v1
kind: Service
metadata:
  name: hasura-secret-refresh-service
spec:
  selector:
    app: hasura-secret-refresh
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5353
  type: ClusterIP


---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hasura-secret-refresh-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  labels:
    app: hasura-secret-refresh-deployment
spec:
  ingressClassName: nginx
  rules:
    -
      http:
        paths:
          - backend:
              service:
                name: hasura-secret-refresh-service
                port:
                  number: 80
            pathType: ImplementationSpecific
            path: /(|$)(.*)/
