apiVersion: v1
kind: Service
metadata:
  name: hasura-secret-refresh-service
spec:
  selector:
    app: hasura-secret-refresh
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort